### ISSUE TITLE
train_CAMELYON_BagDistillationDSMIL_SharedEnc_Similarity_StuFilterSmoothed_DropPos

### ISSUE THREAD

**Issue by ZhangRan24** [miccaiif/WENO#2]
We look forward to uploading train_CAMELYON_BagDistillationDSMIL_SharedEnc_Similarity_StuFilterSmoothed_DropPos.py

**Comment by HardworkingLittlequ** [comment]
Hello! Thanks for your attention! We have uploaded the code.
